#Default Port
server:
  port: 8084

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/estimation
    username: root
    password: Sus@281996
    driver-class-name: com.mysql.cj.jdbc.Driver




